name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh

      - name: Check for package.json changes
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'package.json'; then
            echo "PACKAGE_CHANGED=true" >> $GITHUB_ENV
          else
            echo "PACKAGE_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Deploy to AWS (Light)
        if: env.PACKAGE_CHANGED == 'false'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.AWS_SSH_HOST }}
          SSH_USER: ${{ secrets.AWS_SSH_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST << EOF
            cd fiveguys_frontend/
            git stash
            git pull origin main
          EOF

      - name: Deploy to AWS (Full)
        if: env.PACKAGE_CHANGED == 'true'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.AWS_SSH_HOST }}
          SSH_USER: ${{ secrets.AWS_SSH_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST << EOF
            cd fiveguys_frontend/
            git stash
            docker system prune -a -f
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
