 name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Install SSH client
       run: |
         sudo apt-get update
         sudo apt-get install -y ssh

     - name: Deploy to AWS
       env:
         SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
         SSH_HOST: ${{ secrets.AWS_SSH_HOST }}
         SSH_USER: ${{ secrets.AWS_SSH_USER }}
       run: |
         echo "$SSH_PRIVATE_KEY" > key.pem
         chmod 600 key.pem
         ssh -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST << EOF
           cd fiveguys_frontend/
           git pull origin main
           docker-compose down
           docker-compose up -d --build
         EOF
